version: '3.8'
services:
  # AWS X-Ray Daemon
  xray-daemon:
    image: amazon/aws-xray-daemon
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-ap-southeast-1}
    ports:
      - "2000:2000/udp"
      - "2000:2000/tcp"
    command: ["--local-mode", "--bind=0.0.0.0:2000", "--log-level=debug"]  # Add debug logging
    restart: on-failure

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.70.0
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-ap-southeast-1}
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
      - "8888:8888"  # Metrics endpoint
    depends_on:
      - xray-daemon
    restart: on-failure
    
  db:
    image: postgres:13.9-alpine  # Specifying exact minor version
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trades
    ports:
      - "5432:5432"

  trade_service:
    build: ./trade_service
    ports:
      - "5001:5001"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-ap-southeast-1}
      - OTEL_SERVICE_NAME=trade-service
      - OTEL_RESOURCE_ATTRIBUTES=service.name=trade-service,deployment.environment=development
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_PYTHON_DISABLED_INSTRUMENTATIONS=
      - LOG_GROUP_NAME=/trading-app/trade-service
      - FLASK_ENV=development
      - WERKZEUG_DEBUG_PIN=off
    depends_on:
      - db
      - otel-collector
      - xray-daemon
    restart: on-failure

  portfolio_service:
    build: ./portfolio_service
    ports:
      - "5002:5002"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-ap-southeast-1}
      - OTEL_SERVICE_NAME=portfolio-service
      - OTEL_RESOURCE_ATTRIBUTES=service.name=portfolio-service,deployment.environment=development
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_PYTHON_DISABLED_INSTRUMENTATIONS=
      - LOG_GROUP_NAME=/trading-app/portfolio-service
      - FLASK_ENV=development
      - WERKZEUG_DEBUG_PIN=off
    depends_on:
      - db
      - otel-collector
      - xray-daemon
    restart: on-failure

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - trade_service
      - portfolio_service
